#!/bin/bash
# 更新为 networkservice 自动获取活动链接

# 若命令失败让脚本退出 
set -o errexit
# 若未设置的变量被使用让脚本退出 
set -o nounset

# 设置环境变量
PATH=$PATH:/usr/local/bin/:/opt/homebrew/bin:~/.user_shell_scripts

# 设置 IP， 子网， 下一跳路由
net_ip="192.168.0.3 255.255.225.0 192.168.0.2"
net_dns="192.168.0.2"

# 获取活动连接
networkservice | cut -d',' -f1 | while read -r i; do 
  # 设置网络服务的 IP， 子网， 下一跳路由
  if [ "$i" = "USB 10/100/1000 LAN" ]; then
      networksetup -setmanual "$i" $net_ip;
      # 设置 dns
      networksetup -setdnsservers "$i" $net_dns ;
  fi
  if [ "$i" = "Wi-Fi" ]; then
      networksetup -setmanual "$i" $net_ip;
      # 设置 dns
      networksetup -setdnsservers "$i" $net_dns;
  fi
done

# 通知
osascript -e 'display notification "networksetup" with title "🗼网络服务 IP 已修改!" sound name "Glass"'

exit