#!/bin/bash
# openwrt
# 若命令失败让脚本退出 
set -o errexit

# 设置环境变量
# PATH=$PATH:/usr/local/bin/:/opt/homebrew/bin
# 设置代理
# export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890

# 设置订阅文件路径
nodepath="/mnt/sda3/.node"

# 获取订阅连接
sslink="$(grep 'ss=' "$nodepath" | cut -d'=' -f2-)"
ssrlink="$(grep 'ssr=' "$nodepath" | cut -d'=' -f2-)"
mosulink="$(grep 'mosu=' "$nodepath" | cut -d'=' -f2-)"

# 设置源路径
sspath="/tmp/ssrcloud_ss"
ssrpath="/tmp/ssrcloud_ssr"
mosupath="/tmp/mosu"
# 设置目标路径
destpath=
# 设置日志路径
logspath="/mnt/sda3/rclone_ssrcloud.log"

# 开始下载
curl "$sslink" -o "$sspath"
curl "$ssrlink" -o "$ssrpath"
curl "$mosulink" -o "$mosupath"
#  上传到 Onedrive
rclone copy "$sspath" onedrive:科学上网/订阅 -P --log-file "$logspath" --log-level INFO
rclone copy "$ssrpath" onedrive:科学上网/订阅 -P --log-file "$logspath" --log-level INFO
rclone copy "$mosupath" onedrive:科学上网/订阅 -P --log-file "$logspath" --log-level INFO

# 清除
rm -f "$sspath" "$ssrpath" "$mosupath"

exit 0