#!/bin/bash
# 若命令失败让脚本退出 
set -o errexit
# 设置环境变量
# PATH=$PATH:/usr/local/bin/
# 先同步一次
# 同步"Services"文件夹内容到"服务",排除 '_gsdata_' 'QuickLook' '*~.workflow'
rsync -cavu --delete --delete-excluded --exclude '_gsdata_' --exclude 'QuickLook' --exclude '*~.workflow' "/Users/Sengoku/Library/Services/" "/Users/Sengoku/Git/MacOS-Automator/服务"
# 通知
osascript -e 'display notification "Services 🔜 Git 服务已启动!" with title "fswatch-rsync" sound name "Glass"'
# 监视文件夹并同步
/usr/local/bin/fswatch -0 -l 5 --event "Created" --event "Updated" --event "Removed" --event "Renamed" --event "OwnerModified" --event "MovedFrom" --event "MovedTo" -e "QuickLook" -e "*~.workflow" "/Users/Sengoku/Library/Services" | while read -d "" event; do 
	# 同步"Services"文件夹内容到"服务",排除 '_gsdata_' 'QuickLook' '*~.workflow'
	rsync -cavu --delete --delete-excluded --exclude '_gsdata_' --exclude 'QuickLook' --exclude '*~.workflow' "/Users/Sengoku/Library/Services/" "/Users/Sengoku/Git/MacOS-Automator/服务"
	osascript -e 'display notification "🔄'"${event}"'" with title "fswatch-rsync" sound name "Glass"'
	echo "${event} was rsynced" >> /Users/Sengoku/Git/MacOS-Automator/rsync.log 2>&1
done